sudo: false
script:
- cd builder && RELEASE_VERSION="${TRAVIS_TAG:1}" ./build-latest
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "XyKkvK7dmt9oVqcNaMojgw+vLQ0Q8VBf4K3LWgZHJJbPBUTrLRTNu5JXVB0kvmTZYSdVu7HHZ2LZJxsTac7frnzbMvNim0IfToJa4juW7fF50D+h84T1/T+fl4Q/OKWBDMW+GwhX4dSUygLAznojObwcxQjsSC5ARrBzlBpOjb0="
  file:
    - $HOME/dist/*.tar.gz
  file_glob: true
  on:
    repo: just-containers/s6-overlay
    branch: master
    tags: true
